# Generated by Django 5.2.3 on 2025-07-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pin',
            field=models.CharField(default='nnnnn', max_length=200),
            preserve_default=False,
        ),
    ]
